---
title: "Remote Sensing Imagery Module: Introduction"
author: "Elizabeth Madin"
date: "20/05/2021"
output: 
  github_document
  #html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary

* Overview of 1) the module, 2) remote sensing as a field.
* Discussion of LaRue et al. and discuss/brainstorm project ideas. 
* Later in the week, we'll hear a talk about and Elizabeth's journey integrating field ecology with remote sensing imagery (with no geospatial background).

## Goals

* Develop an understanding of remote sensing as a field and some ways it can be used in marine science
* Start to visualise how you may be able to harness the power of geospatial data in your work
* Start thinking about geospatial-relevent ?s to ask/answer in your own research

## Components

* Introduction to the module and overview of what we'll do in it
* Overview of remote sensing as a field (lecture)
* Questions/brief discussion
* Discussion of LaRue et al. (2016) Conservation Biology
* Brainstorming/discussing ideas for how to use remote sensing in your own research

## Discussion points & questions

#### LaRue et al. (2016) Con. Biol.

* Not just relevant to wildlife obaservation - also relevant to habitat features (e.g., grazing features; coastal land loss; etc.)
* Useful paper because farily non-technical, but conveys key technical points considerations/limitations

* Based on the criteria they give, can you think of other types of animals/habitats that are a) well-suited b) not well-suited to this type of analysis?
* Can you think of something in your own system (or research, or interest) that could be measured by VHR satellite imagery?
* What factors might affect the likelihood of getting accurate results for such analyses?
    + e.g., the way the detection probability of Weddell seals was affected by sea ice conditions
    
* Discussion questions?

* **GOAL**: write down 2-3 things (animals, features, processes, etc.) that you could measure in your system (or beyond) that might be expected to change over time and/or over space
    + Do they require ground-truthing?
    + What potential issues can you foresee?


